name: Scheduled work
on:
  push:
    branches: main
  schedule:
    - cron: '*/3 * * * *'

jobs:
  hello_world:
    runs-on: centos-latest
    steps:
      - name: Echo current time
        run: echo "The current server time is $(date)"
